<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseStyle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('style');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('style', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('notes', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Beer as Beers', array(
             'local' => 'id',
             'foreign' => 'style'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}