<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBeer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('beer');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('author', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('style', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('brewery', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('notes', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('rating', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => '1',
             ));
        $this->hasColumn('abv', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('ibu', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('User', array(
             'local' => 'author',
             'foreign' => 'id'));

        $this->hasOne('Style', array(
             'local' => 'style',
             'foreign' => 'id'));

        $this->hasOne('Brewery', array(
             'local' => 'brewery',
             'foreign' => 'id'));

        $this->hasMany('Movie', array(
             'refClass' => 'FeaturedPair',
             'local' => 'beer_id',
             'foreign' => 'movie_id'));

        $this->hasMany('FeaturedPair as FeaturedPairs', array(
             'local' => 'id',
             'foreign' => 'beer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}