<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMovie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('movie');
        $this->hasColumn('id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('author', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('rating', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => '1',
             ));
        $this->hasColumn('year', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('nfid', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('runtime', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('synopsis', 'string', 2000, array(
             'type' => 'string',
             'length' => '2000',
             ));
        $this->hasColumn('nflink', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('nfsimilar', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('User', array(
             'local' => 'author',
             'foreign' => 'id'));

        $this->hasMany('Beer', array(
             'refClass' => 'FeaturedPair',
             'local' => 'movie_id',
             'foreign' => 'beer_id'));

        $this->hasMany('Genre as Genres', array(
             'local' => 'id',
             'foreign' => 'movie_id'));

        $this->hasMany('FeaturedPair as FeaturedPairs', array(
             'local' => 'id',
             'foreign' => 'movie_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}