generator:
  class: sfDoctrineGenerator
  param:
    model_class:           FeaturedPair
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          featured_pair
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Featured Pairings
        display: [ id, =beerName, =movieName]
        table_method: getJoinedQuery
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
