default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [ /sfDoctrinePlugin/css/global, /sfDoctrinePlugin/css/default, admin]

  javascripts:    []

  has_layout:     on
  layout:         layout
