<?php
// auto-generated by sfRoutingConfigHandler
// date: 2012/10/10 05:50:29
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'homepage',
  'action' => 'index',
), array (
), array (
)),
'login' => new sfRoute('/login/:movie_id/:beer_id/:queue', array (
  'module' => 'homepage',
  'action' => 'login',
), array (
), array (
)),
'share_movie' => new sfRoute('/share/:movie_id/:beer_id', array (
  'module' => 'homepage',
  'action' => 'index',
), array (
), array (
)),
'add_movie' => new sfRoute('/add_movie/:movie_id/:beer_id/:queue', array (
  'module' => 'homepage',
  'action' => 'add_movie',
), array (
), array (
)),
'pairingTypes' => new sfRoute('/pick/step1', array (
  'module' => 'homepage',
  'action' => 'pairingTypes',
), array (
), array (
)),
'pairingPicks' => new sfRoute('/pick/step2', array (
  'module' => 'homepage',
  'action' => 'pairingPicks',
), array (
), array (
)),
'privacy' => new sfRoute('/privacy', array (
  'module' => 'homepage',
  'action' => 'privacy',
), array (
), array (
)),
'about' => new sfRoute('/about', array (
  'module' => 'homepage',
  'action' => 'about',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
