<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Beer extends BaseBeer
{
	public function __toString()
	{
		return $this->label;
	}

	public function getShopLink()
	{
		$term = rawurlencode($this->label);
		return "http://www.bevmo.com/Shop/ProductList.aspx/_/D-{$term}/N-/Ntt-{$term}?DNID=Home&Dx=mode%2Bmatchany&fromsearch=true&Ntk=All&Ntx=mode%2Bmatchany";
	}
}