<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Beer extends BaseBeer
{
	public function __toString()
	{
		return $this->label;
	}
	
	public function getShopLink()
	{
		$term = urlencode($this->label);
		return "http://www.bevmo.com/Shop/ProductList.aspx?Ntt={$term}&N=0&Ntx=mode%2bmatchall&Nty=1&D={$term}&Ntk=All&Dx=mode%2bmatchall";
	}
}