<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeaturedPair extends BaseFeaturedPair
{
	public function getBeerName()
	{
		return $this->getBeer();
	}

	public function getMovieName()
	{
		return $this->Movie;
	}
}