<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GenreTable extends Doctrine_Table
{
	public function getDropDownArray()
	{
		$q = $this->createQuery('g')
			->select('DISTINCT g.genre')
			->orderBy('g.genre ASC');
		
		$return = array();
		foreach($q->setHydrationMode(Doctrine::HYDRATE_NONE)->execute() as $row)
		{
			$return[$row[0]] = $row[0];
		}
		
		return $return;
	}
}