<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Genre extends BaseGenre
{
	public function __toString()
	{
		return $this->genre;
	}
	
	public function getGenreSafe()
	{
		return "'{$this->genre}'";
	}
}