<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovieTable extends Doctrine_Table
{
	public function getIdByGenreQuery($term, array $ids)
	{
		$q = self::getExclusionQuery($ids)
			->leftJoin('m.Genres g')
			->andWhere('g.genre LIKE ?', "%$term%");

		return $q;
	}

	public function getIdByKeywordQuery($term, array $ids)
	{
		$q = self::getExclusionQuery($ids)
			->leftJoin('m.Genres g');

		$term = preg_replace("/-{2,}|[\.\-][\s'\"]|[:;,_]|\.$/"," ' ",$term);
    $term = preg_replace("/([A-Z])\./","$1",$term);
    $common_words = array(" & "," of "," the "," in "," a "," an "," for "," on ", " vs. ");
    $term = str_replace($common_words," ",$term);
		foreach(str_word_count($term, 1) as $word)
		{
			$q->orWhere('m.synopsis LIKE ?', "%{$word}%");
			$q->orWhere('g.genre LIKE ?', "%{$word}%");
		}
		return $q;
	}

	public function getExclusionQuery(array $ids)
	{
		$q = $this->createQuery('m')
			->select('m.id')
			->whereNotIn('m.id', $ids);

		return $q;
	}
	
	public function getByGenreQuery(array $genres)
	{
		$q = $this->createQuery('m')
			->leftJoin('m.Genres g')
			->whereIn('g.genre', $genres)
			->orderBy('m.title ASC');
			
		return $q;
	}
}