<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Movie extends BaseMovie
{
	public function __toString()
	{
		return $this->title;
	}

	public static function createFromNf($nfid)
	{
		$nfid = (string) $nfid;
		$movie = new Movie();
		if(!empty($nfid))
		{
			$data = Netflix::catalogDetail($nfid);
			$movie->image = $data['image'];
			$movie->title = $data['title'];
			$movie->rating = $data['rating'];
			$movie->year = $data['year'];
			$movie->nfid = $data['id'];
			$movie->runtime = $data['runtime'];
			$movie->synopsis = $data['synopsis'];
			$movie->nflink = $data['link'];
			$movie->nfsimilar = $data['similar'];
			foreach($data['genre'] as $v)
			{
				$movie->Genres[]->genre = $v;
			}
		}
		return $movie;
	}
}