<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends BaseUser
{
	const DISABLED_ROLE = 'disabled';
	const NORMAL_ROLE = 'normal';
	const ADMIN_ROLE = 'admin';
	const SECRET = 'CenterEnslavedVertebrae';

	public function __toString()
	{
		return $this->username;
	}

	public function setPassword($v)
	{
		return $this->_set('password', self::pwHash($v));
	}

	public static function pwHash($v)
	{
		$v = (string) $v;
		return md5(hash_hmac('sha1',$v,self::SECRET));
	}
}