<?php
// auto-generated by sfRoutingConfigHandler
// date: 2012/10/10 05:55:36
return array(
'featured_pair' => new sfDoctrineRouteCollection(array (
  'model' => 'FeaturedPair',
  'module' => 'featured_pair',
  'prefix_path' => 'featured_pair',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'featured_pair',
  'requirements' => 
  array (
  ),
)),
'lookup_movie' => new sfRoute('/movie/lookup', array (
  'module' => 'movie',
  'action' => 'lookup',
), array (
), array (
)),
'brewery' => new sfDoctrineRouteCollection(array (
  'model' => 'Brewery',
  'module' => 'brewery',
  'prefix_path' => 'brewery',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'brewery',
  'requirements' => 
  array (
  ),
)),
'style' => new sfDoctrineRouteCollection(array (
  'model' => 'Style',
  'module' => 'style',
  'prefix_path' => 'style',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'style',
  'requirements' => 
  array (
  ),
)),
'beer' => new sfDoctrineRouteCollection(array (
  'model' => 'Beer',
  'module' => 'beer',
  'prefix_path' => 'beer',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'beer',
  'requirements' => 
  array (
  ),
)),
'movie' => new sfDoctrineRouteCollection(array (
  'model' => 'Movie',
  'module' => 'movie',
  'prefix_path' => 'movie',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'movie',
  'requirements' => 
  array (
  ),
)),
'user' => new sfDoctrineRouteCollection(array (
  'model' => 'User',
  'module' => 'user',
  'prefix_path' => 'user',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'user',
  'requirements' => 
  array (
  ),
)),
'login' => new sfRoute('/security/login', array (
  'module' => 'security',
  'action' => 'login',
), array (
), array (
)),
'logout' => new sfRoute('/security/logout', array (
  'module' => 'security',
  'action' => 'logout',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'homepage',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
