<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/10 06:19:38
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
