<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Backend extends Doctrine_Migration
{
	public function up()
	{
		$this->addColumn('beer', 'image', 'string', array('length'=>'255'));
		$this->addColumn('beer', 'rating', 'decimal', array('scale'=>'1'));
		$this->addColumn('style', 'notes', 'string');
		$this->addColumn('style', 'image', 'string', array('length'=>'255'));
		$this->addColumn('brewery', 'image', 'string', array('length'=>'255'));
	}

	public function down()
	{
		$this->removeColumn('beer', 'image');
		$this->removeColumn('beer', 'rating');
		$this->removeColumn('style', 'notes');
		$this->removeColumn('style', 'image');
		$this->removeColumn('brewery', 'image');
	}
}