<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/10 05:56:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=gbbm',
  'username' => 'gbbmuser',
  'password' => 'drunkfilm',
  'name' => 'doctrine',
)),);
